### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HDVinnie** [pxgamer/webd-torr#1]
This looks promising. Just curious if this is functional yet? Is there a way to just add torrent file to client and it download? Or only via the TMDB api and then I guess shows hits from public trackers? Couldn't tell from Demo site.

**Comment by owenvoke** [comment]
Hi, sorry this is currently not functional at all. I'm still working on it, but I've had to take a break while I work on something slightly more important.

**Comment by HDVinnie** [comment]
ok thanks.....ill follow your git for updates

**Comment by owenvoke** [comment]
Not sure I'll ever finish this really.
